#!/usr/bin/env bash
set -eu

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

main() {
  VIRTUAL_ENV_DISABLE_PROMPT=true
  source "${DIR}/env/bin/activate"
  "${DIR}/pr_tree.py" "$@"
}

main "$@"

